In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../../Data/odi-batting.csv')
df.head()

,Country,Player,Runs,ScoreRate,MatchDate,Weekday,Ground,Versus
0,Afghanistan,Mohammad Shahzad,118.0,97.52,16-02-2010,Tue,Sharjah CA Stadium,Canada
1,Afghanistan,Mohammad Shahzad,110.0,99.09,01-09-2009,Tue,VRA Ground,Netherlands
2,Afghanistan,Mohammad Shahzad,100.0,138.88,16-08-2010,Mon,Cambusdoon New Ground,Scotland
3,Afghanistan,Mohammad Shahzad,82.0,75.92,10-07-2010,Sat,Hazelaarweg,Netherlands
4,Afghanistan,Mohammad Shahzad,57.0,100.00,01-07-2010,Thu,Sportpark Westvliet,Canada

In [5]:
# by default describe() only works on numeric columns 
# but it is good practice to only select the columns you want to work with

select_col = ['Runs','ScoreRate']
df[select_col].describe()

               Runs     ScoreRate
count  55900.000000  55907.000000
mean      22.241413     65.306030
std       25.558363     44.216694
min        0.000000      0.000000
25%        4.000000     37.500000
50%       13.000000     62.650000
75%       32.000000     87.500000
max      200.000000    600.000000

In [7]:
df.shape

(55926, 8)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55926 entries, 0 to 55925
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    55926 non-null  object
 1   Player     55926 non-null  object
 2   Runs       55900 non-null  float64
 3   ScoreRate  55907 non-null  float64
 4   MatchDate  55926 non-null  object
 5   Weekday    55926 non-null  object
 6   Ground     55926 non-null  object
 7   Versus     55926 non-null  object
dtypes: float64(2), object(6)
memory usage: 3.4+ MB

In [ ]:
# now to describe the categorical columns we chosse only the object columns
cat_col = ['Country','Player','Ground','Versus']
df[cat_col].astype('object').describe()

# on numerical columns describe() provides distribution analysis and on 
# categorical columns it provides frequency analysis.

       Country              Player              Ground     Versus
count    55926               55926               55926      55926
unique      22                1936                 178         25
top      India  Sachin R Tendulkar  Sharjah CA Stadium  Australia
freq      6634                 442                3581       7216

In [ ]:
df['MatchDate'] = pd.to_datetime(df['MatchDate'], format='%d-%m-%Y')
df.dtypes # this is how we can check the data types of the columns in our dataframe

Country              object
Player               object
Runs                float64
ScoreRate           float64
MatchDate    datetime64[ns]
Weekday              object
Ground               object
Versus               object
dtype: object

In [16]:
df['MatchDate'].describe()

count                            55926
mean     1999-02-13 18:21:41.577084032
min                1971-01-05 00:00:00
25%                1993-03-19 00:00:00
50%                2000-07-12 00:00:00
75%                2006-09-12 00:00:00
max                2011-10-28 00:00:00
Name: MatchDate, dtype: object

In [ ]:
# df['MatchDate'].describe(datetime_is_numeric=False)

# this is how we can describe the datetime column as numeric column and get the distribution analysis of the dates.
# old style describe() on datetime columns provides frequency analysis of the dates.
# this method no longer works in pandas 2.0 and above. It will throw an error if you try to use it.

In [22]:
print(pd.__version__)

2.3.3